
import __ASTRO_IMAGE_IMPORT_Z1J03Sz from "../../assets/MError.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FMeRror.md";
import __ASTRO_IMAGE_IMPORT_1lHo7F from "../../assets/kcf-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkcf-technologies.md";
import __ASTRO_IMAGE_IMPORT_FrEem from "../../assets/kcf-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkcf-technologies.md";
import __ASTRO_IMAGE_IMPORT_bUl3 from "../../assets/kcf-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkcf-technologies.md";
import __ASTRO_IMAGE_IMPORT_ZF3Nxg from "../../assets/kcf-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkcf-technologies.md";
import __ASTRO_IMAGE_IMPORT_Z1ljxqz from "../../assets/kcf-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkcf-technologies.md";
import __ASTRO_IMAGE_IMPORT_1tOC7O from "../../assets/441-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgraphics.md";
import __ASTRO_IMAGE_IMPORT_Z10u2UJ from "../../assets/441-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgraphics.md";
import __ASTRO_IMAGE_IMPORT_1znpOD from "../../assets/441-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgraphics.md";
import __ASTRO_IMAGE_IMPORT_Z1dfHE0 from "../../assets/441-4-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgraphics.md";
import __ASTRO_IMAGE_IMPORT_1N6lIX from "../../assets/441-5-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgraphics.md";
import __ASTRO_IMAGE_IMPORT_ZGdjjA from "../../assets/441-5-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgraphics.md";
import __ASTRO_IMAGE_IMPORT_gTjsr from "../../assets/workoutbuddy2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fworkout-buddy.md";
import __ASTRO_IMAGE_IMPORT_iQycP from "../../assets/workoutbuddy4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fworkout-buddy.md";
export default new Map([["../../assets/MError.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FMeRror.md", __ASTRO_IMAGE_IMPORT_Z1J03Sz], ["../../assets/kcf-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkcf-technologies.md", __ASTRO_IMAGE_IMPORT_1lHo7F], ["../../assets/kcf-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkcf-technologies.md", __ASTRO_IMAGE_IMPORT_FrEem], ["../../assets/kcf-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkcf-technologies.md", __ASTRO_IMAGE_IMPORT_bUl3], ["../../assets/kcf-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkcf-technologies.md", __ASTRO_IMAGE_IMPORT_ZF3Nxg], ["../../assets/kcf-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkcf-technologies.md", __ASTRO_IMAGE_IMPORT_Z1ljxqz], ["../../assets/441-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgraphics.md", __ASTRO_IMAGE_IMPORT_1tOC7O], ["../../assets/441-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgraphics.md", __ASTRO_IMAGE_IMPORT_Z10u2UJ], ["../../assets/441-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgraphics.md", __ASTRO_IMAGE_IMPORT_1znpOD], ["../../assets/441-4-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgraphics.md", __ASTRO_IMAGE_IMPORT_Z1dfHE0], ["../../assets/441-5-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgraphics.md", __ASTRO_IMAGE_IMPORT_1N6lIX], ["../../assets/441-5-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgraphics.md", __ASTRO_IMAGE_IMPORT_ZGdjjA], ["../../assets/workoutbuddy2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fworkout-buddy.md", __ASTRO_IMAGE_IMPORT_gTjsr], ["../../assets/workoutbuddy4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fworkout-buddy.md", __ASTRO_IMAGE_IMPORT_iQycP]]);
		